# Generated by Django 3.1.2 on 2020-11-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201126_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Listing'),
        ),
    ]
