# Generated by Django 3.1.2 on 2020-11-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201126_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_by',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='Bid_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bids',
            name='Bid_on',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.listing')),
                ('ofuser', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ofuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
