# Generated by Django 3.1.2 on 2020-12-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201201_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Listed_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Listed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
