# Generated by Django 3.1.2 on 2020-12-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201206_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Bid_Price',
            field=models.IntegerField(blank=True),
        ),
    ]
