# Generated by Django 3.1.2 on 2020-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201211_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
